//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int IdCompra { get; set; }
        public short idUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual CompraDetalle CompraDetalle { get; set; }
    }
}
