//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int id { get; set; }
        public long Producto { get; set; }
        public int Venta { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Producto Producto1 { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
