//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Venta_Tiempo
    {
        public long IdVenta { get; set; }
        public long Fk_Pc { get; set; }
        public short Fk_Usuario { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_fin { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
