//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estante
    {
        public Estante()
        {
            this.Productoes = new HashSet<Producto>();
        }
    
        public int IdEstante { get; set; }
        public string NombreEstante { get; set; }
        public string DescripciónEstante { get; set; }
    
        public virtual ICollection<Producto> Productoes { get; set; }
    }
}
