//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int IdEstado { get; set; }
        public int Estado1 { get; set; }
        public string Descripción_estado { get; set; }
        public Nullable<short> FKUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
