//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CyberElIngeEntities : DbContext
    {
        public CyberElIngeEntities()
            : base("name=CyberElIngeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compra> Compras { get; set; }
        public DbSet<CompraDetalle> CompraDetalles { get; set; }
        public DbSet<Detalle_Venta_Tiempo> Detalle_Venta_Tiempo { get; set; }
        public DbSet<PC> PCs { get; set; }
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Estante> Estantes { get; set; }
        public DbSet<Producto> Productoes { get; set; }
        public DbSet<Proveedor> Proveedors { get; set; }
        public DbSet<ModuloPrincipal> ModuloPrincipals { get; set; }
        public DbSet<Modulo> Modulos { get; set; }
        public DbSet<Perfile> Perfiles { get; set; }
        public DbSet<PerfilModulo> PerfilModuloes { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<UsuarioDetalle> UsuarioDetalles { get; set; }
        public DbSet<DetalleVenta> DetalleVentas { get; set; }
        public DbSet<Estado> Estadoes { get; set; }
        public DbSet<Venta> Ventas { get; set; }
        public DbSet<Factura> Facturas { get; set; }
        public DbSet<Imprimir_Facturas> Imprimir_Facturas { get; set; }
        public DbSet<Vista1> Vista1 { get; set; }
        public DbSet<VistaProductoMasVendido> VistaProductoMasVendidoes { get; set; }
        public DbSet<VistaVentasPorMe> VistaVentasPorMes { get; set; }
    }
}
