//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.PerfilModuloes = new HashSet<PerfilModulo>();
            this.Perfiles = new HashSet<Perfile>();
        }
    
        public short IdModulos { get; set; }
        public string DescripcionModulo { get; set; }
        public bool EstadoModulo { get; set; }
        public short FKModuloPrincipal { get; set; }
    
        public virtual ModuloPrincipal ModuloPrincipal { get; set; }
        public virtual ICollection<PerfilModulo> PerfilModuloes { get; set; }
        public virtual ICollection<Perfile> Perfiles { get; set; }
    }
}
