//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfile
    {
        public Perfile()
        {
            this.PerfilModuloes = new HashSet<PerfilModulo>();
            this.Usuarios = new HashSet<Usuario>();
            this.Modulos = new HashSet<Modulo>();
        }
    
        public short IdPerfil { get; set; }
        public string DescripcionPerfil { get; set; }
        public bool EstadoPerfil { get; set; }
    
        public virtual ICollection<PerfilModulo> PerfilModuloes { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<Modulo> Modulos { get; set; }
    }
}
