//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.CompraDetalles = new HashSet<CompraDetalle>();
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public long IdProducto { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal PrecioCosto { get; set; }
        public int Categoria { get; set; }
        public int Proveedor { get; set; }
        public Nullable<int> Estante { get; set; }
        public string Tipo_Impuesto { get; set; }
    
        public virtual ICollection<CompraDetalle> CompraDetalles { get; set; }
        public virtual Categoria Categoria1 { get; set; }
        public virtual Estante Estante1 { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
    }
}
