//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Productoes = new HashSet<Producto>();
        }
    
        public int IdProveedor { get; set; }
        public string Empresa { get; set; }
        public string Vendedor { get; set; }
        public string Contacto { get; set; }
        public string Contacto1 { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Producto> Productoes { get; set; }
    }
}
