//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public int IdVenta { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public decimal Total_Venta { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<decimal> Impuesto_Gravado_15_ { get; set; }
        public Nullable<decimal> Impuesto_Gravado_18_ { get; set; }
        public Nullable<decimal> ISV15_ { get; set; }
        public Nullable<decimal> ISV18_ { get; set; }
        public Nullable<decimal> Importe_Exento { get; set; }
        public Nullable<decimal> Importe_Exonerado { get; set; }
    
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual Estado Estado1 { get; set; }
    }
}
