//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista1
    {
        public string Codigo { get; set; }
        public string Producto { get; set; }
        public int Existencias { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public string Categoria { get; set; }
        public string Proveedor { get; set; }
    }
}
