//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta.Bases_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Venta_Tiempo
    {
        public long IdVenta { get; set; }
        public long Fk_Pc { get; set; }
        public short Fk_Usuario { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_fin { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual PC PC { get; set; }
    }
}
