//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta.Bases_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioDetalles
    {
        public short PKUsuario { get; set; }
        public string userNombre { get; set; }
        public string userApellido { get; set; }
        public string userTelefono { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
