//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta.Bases_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVentas = new HashSet<DetalleVentas>();
        }
    
        public int IdVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<short> idUsuario { get; set; }
    
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
    }
}
